#!/usr/bin/env python 
import drawtree
from parse import *

sentence = unparsed(sys.argv[1:]+['ol'])
parse(sentence)
for i in range(0,len(sentence)-1):
	if sentence[i].head != dummy:
		print(drawtree.drawPhrase(sentence[i]))
